name: 'Check Links'
on:
  push:
  pull_request:

jobs:
  link_check:
    name: 'Link Check'
    uses: NIGMS/NIGMS-Sandbox-Repository-Template/.github/workflows/check-links.yaml@reusable_workflow
    with:
      repo_link_ignore_list: ""