name: 'Check Links'
on:
  push:
  pull_request:

jobs:
  link_check:
    name: 'Link Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Check
        env:
          LINK_IGNORE_LIST: https://www.sciencedirect.com,https://portlandpress.com
        run: |
          python3 .github/workflows/check_links.py